export const SET_DEVICE = "SED_DEVICE";
export const DELETE_DEVICE = "DELETE_DEVICE";
export const ADD_PRODUCER_TRANSPORT = "ADD_PRODUCER_TRANSPORT";
export const REMOVE_PRODUCER_TRANSPORT = "REMOVE_PRODUCER_TRANSPORT";
export const ADD_CONSUMER_TRANSPORT = "ADD_CONSUMER_TRANSPORT";
export const REMOVE_CONSUMER_TRANSPORT = "REMOVE_CONSUMER_TRANSPORT";
export const ADD_PARAM = "ADD_PARAM";

export const ADD_ROOM_NAME = "ADD_ROOM_NAME";
export const SET_IS_ROOM_PUBLIC = "SET_IS_ROOM_PUBLIC";
export const SET_IS_ROOM_STRMED = "SET_IS_ROOM_STRMED";
export const SET_ADMIN_ID = "SET_ADMIN_ID";
export const IS_JOINED_THE_ROOM = "IS_JOINED_THE_ROOM";
export const ADD_TO_GUEST_LIST = "ADD_TO_GUEST_LIST";
export const REMOVE_FROM_GUEST_LIST = "REMOVE_FROM_GUEST_LIST";

export const ADD_CHAT_MESSAGE = "ADD_CHAT_MESSAGE";
export const ADD_PRIVET_MESSAGE = "ADD_PRIVET_MESSAGE";
export const ADD_MESSAGE_TO_CHAT = "ADD_MESSAGE_TO_CHAT";
export const UP_DATE_GUEST_LIST = "UP_DATE_GUEST_LIST";
export const SET_USER_MEDIA = "SET_USER_MEDIA";
export const IS_FREE_TO_JOIN = "IS_FREE_TO_JOIN";
export const REST_STATE = "REST_ROOM_STATE";
export const HIDE_THE_ROOM = "HIDE_THE_ROOM";




